--Departments table 
CREATE TABLE DEPARTMENTS(
DEPT_NO VARCHAR PRIMARY KEY,
DEPT_NAME VARCHAR NOT NULL);

--Employees table
CREATE TABLE EMPLOYEES(
EMP_NO SERIAL PRIMARY KEY,
BIRTH_DATE DATE NOT NULL,
FIRST_NAME VARCHAR NOT NULL,
LAST_NAME VARCHAR NOT NULL,
GENDER VARCHAR(1) NOT NULL,
HIRE_DATE DATE NOT NULL);

--Department employee table
CREATE TABLE DEPT_EMP(
EMP_NO INT,
DEPT_NO VARCHAR,
FROM_DATE DATE NOT NULL,
TO_DATE DATE NOT NULL,
FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO));

--Department Manager table
CREATE TABLE DEPT_MANAGER(
DEPT_NO VARCHAR,
EMP_NO INT,
FROM_DATE DATE NOT NULL,
TO_DATE DATE NOT NULL,
FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO),
FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO));

--Salaries table
CREATE TABLE SALARIES(
EMP_NO INT,
SALARY INT NOT NULL,
FROM_DATE DATE NOT NULL,
TO_DATE DATE NOT NULL,
FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO));

--Titles table
CREATE TABLE TITLES(
EMP_NO INT,
TITLE VARCHAR NOT NULL,
FROM_DATE DATE NOT NULL,
TO_DATE DATE NOT NULL,
FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO));

