--1)
	SELECT E.EMP_NO,E.LAST_NAME,E.FIRST_NAME,E.GENDER,S.SALARY
	FROM EMPLOYEES E, SALARIES S
	WHERE E.EMP_NO = S.EMP_NO
	ORDER BY EMP_NO;
	

--2) 36150 ROWS AFFECTED
	SELECT E.*
	FROM EMPLOYEES E
	WHERE EXTRACT(YEAR FROM E.HIRE_DATE) = 1986;
	
--3)
	SELECT D.DEPT_NO,D.DEPT_NAME,E.EMP_NO AS MANAGER,E.LAST_NAME,E.FIRST_NAME,DM.FROM_DATE,DM.TO_DATE
	FROM DEPARTMENTS D, EMPLOYEES E, DEPT_MANAGER DM
	WHERE DM.DEPT_NO = D.DEPT_NO
	AND DM.EMP_NO = E.EMP_NO
	AND EXTRACT(YEAR FROM DM.TO_DATE) > EXTRACT(YEAR FROM CURRENT_TIMESTAMP);
	
--4)
	SELECT E.EMP_NO,E.LAST_NAME,E.FIRST_NAME,D.DEPT_NAME
	FROM EMPLOYEES E, DEPARTMENTS D, DEPT_EMP DE
	WHERE DE.EMP_NO = E.EMP_NO
	AND DE.DEPT_NO = D.DEPT_NO
	ORDER BY E.EMP_NO;
	
--5)20 ROWS RETREIVED
	SELECT E.* FROM EMPLOYEES E
	WHERE E.FIRST_NAME LIKE 'Hercules'
	AND E.LAST_NAME LIKE 'B%';

--6)
	SELECT E.EMP_NO,E.LAST_NAME,E.FIRST_NAME,D.DEPT_NAME
	FROM EMPLOYEES E, DEPT_EMP DE, 
		 (SELECT DEPT_NO,DEPT_NAME
		  FROM DEPARTMENTS
		  WHERE DEPT_NAME LIKE 'Sales') D
	WHERE DE.DEPT_NO = D.DEPT_NO
	AND DE.EMP_NO = E.EMP_NO;
	
--7)
	SELECT E.EMP_NO,E.LAST_NAME,E.FIRST_NAME,D.DEPT_NAME
	FROM EMPLOYEES E, DEPT_EMP DE, 
		 (SELECT DEPT_NO,DEPT_NAME
		  FROM DEPARTMENTS
		  WHERE DEPT_NAME IN ('Sales','Development')) D
	WHERE DE.DEPT_NO = D.DEPT_NO
	AND DE.EMP_NO = E.EMP_NO;
	
--8)
	SELECT E.LAST_NAME,COUNT(E.LAST_NAME)
	FROM EMPLOYEES E
	GROUP BY E.LAST_NAME
	ORDER BY E.LAST_NAME DESC;